/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: IsaacTheMaverick (https://sketchfab.com/IsaacTheMaverick)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-room-a6bf7976f3ac401e96907aa5b8a0c1c1
title: Low Poly Room
*/

import React, { useRef } from 'react'
import { useGLTF, OrbitControls } from '@react-three/drei'
import { Canvas, useFrame, useThree, useLoader } from '@react-three/fiber'
import { Box } from '@mui/material'

function TtRoom(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/low_poly_room/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}
    position={[0, -4, 0]}
    scale={[0.04, 0.04, 0.04]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-126.86, 16.43, 29.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[16.09, 16.09, 16.09]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_PC_Glass_0.geometry}
              material={materials.PC_Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_UberTexture_0.geometry}
              material={materials.UberTexture}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_Floor_0.geometry}
              material={materials.Floor}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

export default function TestRoom(props) {
    const cameraPosition = [30, 20, 30]

    return (
    <Box sx={{
        width: '100vw',
        height: '100vh',
      }}>
        <Canvas style={{ height: "100vh", width: "100vw" }}
        orthographic camera={{ zoom: 40, position: cameraPosition }}>
        <OrbitControls />
        <ambientLight />
        <pointLight position={[10, 10, 10]} />
        <TtRoom />
        </Canvas>
     </Box>
    );
}



useGLTF.preload('/low_poly_room/scene.gltf')