/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: EduardoIkeda (https://sketchfab.com/EduardoIkeda)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/air-conditioning-control-eletrolux-6dff80806c54455895c698e217260d45
title: Air conditioning control - Eletrolux
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Aircontroller(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/air_conditioning_control_-_eletrolux/scene.gltf')
    return (
        <group ref={group} dispose={null}>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.4, 0.4, 0.4]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0.01, 0.15, 0.06]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface1_Controller_0.geometry}
                            material={materials.Controller}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pPlane1_Plane_0.geometry}
                        material={materials.Plane}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/air_conditioning_control_-_eletrolux/scene.gltf')