/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: maxsbond.work (https://sketchfab.com/maxsbond.work)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/air-condition-daikin-26b0f7c8472741f4b85b889cf3b1d870
title: Air condition Daikin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Airconditional(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/air_condition_daikin/scene.gltf')
    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.007, 0.005, 0.005]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials.wire_000000000}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/air_condition_daikin/scene.gltf')