/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Logotyp (https://sketchfab.com/Logotyp)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/arcade-machine-a914bf3651e3496ea708dc0782eca212
title: arcade machine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Arcade(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/arcade_machine/scene.gltf')
    return (
        <group scale={[3, 3, 3]} ref={group} dispose={null}>
            <group
                position={[0.38, 0, -0.51]}
                rotation={[-Math.PI / 2, 0, -0.61]}
                scale={[0.38, 0.38, 0.38]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.initialShadingGroup}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={materials.lambert2SG}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.lambert3SG}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.lambert5SG}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials.lambert6SG}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials.lambert7SG}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.lambert8SG}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/arcade_machine/scene.gltf')
