/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: peterthanh84.tl (https://sketchfab.com/peterthanh84.tl)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/art-frame-25b86d7272e849f0967149243601bcbf
title: Art Frame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Artframe(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/art_frame/scene.gltf')
    return (
        <group scale={[2, 2, 2]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial.geometry}
                        material={materials['06___Default']}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/art_frame/scene.gltf')