/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dimaponomar2019 (https://sketchfab.com/dimaponomar2019)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/backpack-low-poly-d7225bdd1d6c42d992485d72438cab28
title: Backpack low-poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Backpack(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/backpack_low-poly/scene.gltf')
    return (
        <group scale={[0.005, 0.005, 0.005]} ref={group} dispose={null}>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag_low_����������������_0'].geometry}
                            material={nodes['bag_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag001_low_����������������_0'].geometry}
                            material={nodes['bag001_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag002_low_����������������_0'].geometry}
                            material={nodes['bag002_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag003_low_����������������_0'].geometry}
                            material={nodes['bag003_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag004_low_����������������_0'].geometry}
                            material={nodes['bag004_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag005_low_����������������_0'].geometry}
                            material={nodes['bag005_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag006_low_����������������_0'].geometry}
                            material={nodes['bag006_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag007_low_����������������_0'].geometry}
                            material={nodes['bag007_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag008_low_����������������_0'].geometry}
                            material={nodes['bag008_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag009_low_����������������_0'].geometry}
                            material={nodes['bag009_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag010_low_����������������_0'].geometry}
                            material={nodes['bag010_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag011_low_����������������_0'].geometry}
                            material={nodes['bag011_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag012_low_����������������_0'].geometry}
                            material={nodes['bag012_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag013_low_����������������_0'].geometry}
                            material={nodes['bag013_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag014_low_����������������_0'].geometry}
                            material={nodes['bag014_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag015_low_����������������_0'].geometry}
                            material={nodes['bag015_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag016_low_����������������_0'].geometry}
                            material={nodes['bag016_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag017_low_����������������_0'].geometry}
                            material={nodes['bag017_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag018_low_����������������_0'].geometry}
                            material={nodes['bag018_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag019_low_����������������_0'].geometry}
                            material={nodes['bag019_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag020_low_����������������_0'].geometry}
                            material={nodes['bag020_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag021_low_����������������_0'].geometry}
                            material={nodes['bag021_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag022_low_����������������_0'].geometry}
                            material={nodes['bag022_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag023_low_����������������_0'].geometry}
                            material={nodes['bag023_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag024_low_����������������_0'].geometry}
                            material={nodes['bag024_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag025_low_����������������_0'].geometry}
                            material={nodes['bag025_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag026_low_����������������_0'].geometry}
                            material={nodes['bag026_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag027_low_����������������_0'].geometry}
                            material={nodes['bag027_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag028_low_����������������_0'].geometry}
                            material={nodes['bag028_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag029_low_����������������_0'].geometry}
                            material={nodes['bag029_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag030_low_����������������_0'].geometry}
                            material={nodes['bag030_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag031_low_����������������_0'].geometry}
                            material={nodes['bag031_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag032_low_����������������_0'].geometry}
                            material={nodes['bag032_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag033_low_����������������_0'].geometry}
                            material={nodes['bag033_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag034_low_����������������_0'].geometry}
                            material={nodes['bag034_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag035_low_����������������_0'].geometry}
                            material={nodes['bag035_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag036_low_����������������_0'].geometry}
                            material={nodes['bag036_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag037_low_����������������_0'].geometry}
                            material={nodes['bag037_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag038_low_����������������_0'].geometry}
                            material={nodes['bag038_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag039_low_����������������_0'].geometry}
                            material={nodes['bag039_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag040_low_����������������_0'].geometry}
                            material={nodes['bag040_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag041_low_����������������_0'].geometry}
                            material={nodes['bag041_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag042_low_����������������_0'].geometry}
                            material={nodes['bag042_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag043_low_����������������_0'].geometry}
                            material={nodes['bag043_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag044_low_����������������_0'].geometry}
                            material={nodes['bag044_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag045_low_����������������_0'].geometry}
                            material={nodes['bag045_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag046_low_����������������_0'].geometry}
                            material={nodes['bag046_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag047_low_����������������_0'].geometry}
                            material={nodes['bag047_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag048_low_����������������_0'].geometry}
                            material={nodes['bag048_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag049_low_����������������_0'].geometry}
                            material={nodes['bag049_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag050_low_����������������_0'].geometry}
                            material={nodes['bag050_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag051_low_����������������_0'].geometry}
                            material={nodes['bag051_low_����������������_0'].material}
                        />
                    </group>
                    <group
                        position={[-16.76, 43.48, -0.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['bag052_low_����������������_0'].geometry}
                            material={nodes['bag052_low_����������������_0'].material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/backpack_low-poly/scene.gltf')