/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Agustín Hönnun (https://sketchfab.com/Agustin_Honnun)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bathroom-sink-free-agustin-honnun-daf4b17edf874b0fb239e17b2e7d68e4
title: Bathroom Sink [FREE] | Agustin Honnun
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Edges } from '@react-three/drei'

export default function BathSink(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/bathroom_sink_free__agustin_honnun/scene.gltf')
    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, 297.83, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_Ceramica_0.geometry}
                            material={materials.Ceramica}>
                            <Edges
                                color='rgb(200, 200, 200)'
                                threshold={30} />
                        </mesh>
                    </group>
                    <group
                        position={[0, 399.71, -81.59]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Circle001_Goma_0.geometry}
                            material={materials.Goma}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Circle001_Diffuse_0.geometry}
                            material={materials.Diffuse}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Circle001_Metal_0.geometry}
                            material={materials.Metal}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/bathroom_sink_free__agustin_honnun/scene.gltf')