/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cirno (https://sketchfab.com/cirnoB)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sink-cabinet-a-3d4824436000452f9d31f5a77fa43e0b
title: Sink cabinet A
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function BathCabinet(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/sink_cabinet_a/scene.gltf')
    const { actions } = useAnimations(animations, group)
    return (
        <group scale={[4, 4, 4]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[1.05, 1.05, 1.05]}>
                <group scale={[0, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_4.geometry}
                        material={nodes.Object_4.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_5.geometry}
                        material={nodes.Object_5.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_6.geometry}
                        material={materials.CountertopMarble}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={nodes.Object_10.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={nodes.Object_11.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.Plastic_Contertop}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/sink_cabinet_a/scene.gltf')