/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bilgehan.korkmaz (https://sketchfab.com/bilgehan.korkmaz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/simple-bean-bag-chair-c2af3dba43854cfa813ac6407107bfdf
title: Simple Bean Bag Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Binback(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/simple_bean_bag_chair/scene.gltf')
    return (
        <group scale={[2, 2, 2]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial.geometry}
                        material={nodes.defaultMaterial.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_1.geometry}
                        material={nodes.defaultMaterial_1.material}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/simple_bean_bag_chair/scene.gltf')