/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: adadadad5252341 (https://sketchfab.com/adadadad5252341)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cc0-bookshelf-with-books-961af2daa6344e4fba0c7a4c92ff91f8
title: [CC0] Bookshelf with books
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bookshelf(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/cc0_bookshelf_with_books/scene.gltf')
    return (
        <group scale={[3.5, 3.5, 3.5]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials['WoodLight.007']}
                        />
                    </group>
                    <group rotation={[0, 0.03, 0]} scale={[0.97, 0.97, 0.97]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials.BookSet2}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/cc0_bookshelf_with_books/scene.gltf')
