/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Camay (https://sketchfab.com/Camay)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cabinet-a8ca7d4dae9d495f8b6b98ee2321c004
title: Cabinet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cabinet2(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/cabinet/scene.gltf')
    return (
        <group scale={[0.5, 0.5, 0.5]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.Material}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/cabinet/scene.gltf')
