/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: furnny (https://sketchfab.com/furnny)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vitra-eames-plastic-chair-0a45955e2328459d95f403cb00c08b3a
title: Vitra Eames Plastic Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Edges } from '@react-three/drei'

export default function Chair(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/vitra_eames_plastic_chair/scene.gltf')
    return (
        <group scale={[4, 4, 4]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
                <group position={[0, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_2.geometry}
                        material={nodes.Object_2.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_3.geometry}
                        material={nodes.Object_3.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_4.geometry}
                        material={nodes.Object_4.material}>
                        <Edges
                            color='rgb(250, 250, 250)'
                            threshold={25} />
                    </mesh>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_5.geometry}
                        material={nodes.Object_5.material}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/vitra_eames_plastic_chair/scene.gltf')