/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MW (https://sketchfab.com/mw3dart)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chicken-nuggets-f751cf123621413aaf4bac355d944f47
title: Chicken Nuggets
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Chicken(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/chicken_nuggets/scene.gltf')
    return (
        <group scale={[4, 4, 4]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.chicken_nuggets_tylers_LOD00_frozen_entrees_002_M_0.geometry}
                        material={materials.frozen_entrees_002_M}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/chicken_nuggets/scene.gltf')