/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: serrozbif (https://sketchfab.com/serrozbif)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/clock-5d51a5e31ee84792a18046a2a8df8bdd
title: Clock
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Clock(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/clock/scene.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={nodes.Object_2.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={nodes.Object_3.material}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/clock/scene.gltf')
