/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 1-3D.com (https://sketchfab.com/1-3D.com)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/folded-clothes-ca4932da28ea495db1f9969807d9c107
title: Folded clothes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Clothes2(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/folded_clothes/scene.gltf')
    return (
        <group scale={[0.04, 0.04, 0.04]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.blue}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.green}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.red_chamise}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials['red_chamise-dark']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials['dark-red-button']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={materials['blue-trousers']}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/folded_clothes/scene.gltf')