/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DailyArt (https://sketchfab.com/D.art)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/coffee-machine-a6e19d641a2642b4b9ddb68b0c5f3c56
title: Coffee machine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CoffeeMachine(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/coffee_machine/scene.gltf')
    return (
        <group scale={[0.017, 0.017, 0.017]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0.85, 60.16, 15.39]} scale={[67.23, 67.23, 67.23]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials.touming}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={materials.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/coffee_machine/scene.gltf')