/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: The Motion Tree (https://sketchfab.com/themotiontree)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cosmetics-product-b309b65973e64997be6cc267eea3b519
title: Cosmetics Product
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cosmetic(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/cosmetics_product/scene.gltf')
    return (
        <group scale={[0.025, 0.025, 0.025]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials.Kajal}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={materials.Peace_Milk}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={materials.Argan_oil_Rediance}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_15.geometry}
                            material={materials.material}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_18.geometry}
                            material={materials.Absolut}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_21.geometry}
                            material={materials.Mackup_Box}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_24.geometry}
                            material={materials.Perfect_Rediance}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_27.geometry}
                            material={materials.Argan_oil_serum}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_30.geometry}
                            material={materials.Primer_Matt}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_33.geometry}
                            material={materials.Weightless}
                        />
                    </group>
                    <group rotation={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_36.geometry}
                            material={materials.Glass}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/cosmetics_product/scene.gltf')