/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lahcen.el (https://sketchfab.com/Lahcen.el)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sofa-long-sofa-5c2ecc125237498fa610f928fc435db6
title: Sofa - Long Sofa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Couch2(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/long_sofa/scene.gltf')
    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-0.25, 1.11, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={[0.002, 0.0025, 0.0025]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={nodes.Object_4.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5.geometry}
                            material={nodes.Object_5.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={nodes.Object_6.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_7.geometry}
                            material={nodes.Object_7.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_8.geometry}
                            material={nodes.Object_8.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={materials.wood}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_10.geometry}
                            material={materials['03___Default']}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/long_sofa/scene.gltf')