/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OnOne Supplies (https://sketchfab.com/ononesupplies)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dining-table-lowpoly-389cc90cfc3c45d5b5597e493f06edc3
title: Dining Table Lowpoly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function DiningTable(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/dining_table_lowpoly/scene.gltf')
    return (
        <group scale={[0.025, 0.025, 0.025]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-401.08, 348.78, 469.33]} rotation={[0, 0.96, -0.63]} />
                    <group position={[-7.14, 15.19, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Table_Mat_0.geometry}
                            material={nodes.Table_Mat_0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Table_Mat1_0.geometry}
                            material={nodes.Table_Mat1_0.material}
                        />
                    </group>
                    <group position={[-40.9, -27.15, 85.13]}>
                        <group position={[-69.29, 13.31, -11.41]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Chair_2_Mat_0.geometry}
                                material={nodes.Chair_2_Mat_0.material}
                            />
                        </group>
                        <group position={[-68.96, -51.28, 11.41]}>
                            <group position={[0, 0, -45.65]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Leg_3_Mat1_0.geometry}
                                    material={nodes.Leg_3_Mat1_0.material}
                                />
                            </group>
                            <group position={[0, 0, 1.67]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Leg_1_2_Mat1_0.geometry}
                                    material={nodes.Leg_1_2_Mat1_0.material}
                                />
                            </group>
                        </group>
                        <group position={[0, 0, -75]}>
                            <group position={[-69.29, 13.31, -11.41]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Chair_3_Mat_0.geometry}
                                    material={nodes.Chair_3_Mat_0.material}
                                />
                            </group>
                            <group position={[-68.96, -51.28, 11.41]}>
                                <group position={[0, 0, -45.65]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Leg_6_Mat1_0.geometry}
                                        material={nodes.Leg_6_Mat1_0.material}
                                    />
                                </group>
                                <group position={[0, 0, 1.67]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Leg_1_4_Mat1_0.geometry}
                                        material={nodes.Leg_1_4_Mat1_0.material}
                                    />
                                </group>
                            </group>
                        </group>
                        <group position={[0, 0, -150]}>
                            <group position={[-69.29, 13.31, -11.41]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Chair_4_Mat_0.geometry}
                                    material={nodes.Chair_4_Mat_0.material}
                                />
                            </group>
                            <group position={[-68.96, -51.28, 11.41]}>
                                <group position={[0, 0, -45.65]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Leg_9_Mat1_0.geometry}
                                        material={nodes.Leg_9_Mat1_0.material}
                                    />
                                </group>
                                <group position={[0, 0, 1.67]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Leg_1_6_Mat1_0.geometry}
                                        material={nodes.Leg_1_6_Mat1_0.material}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/dining_table_lowpoly/scene.gltf')