/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DailyArt (https://sketchfab.com/D.art)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/european-style-dining-cabinet-c8717576f2244716b3abf321065f2b9a
title: European style dining cabinet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function DiningCabinet(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/european_style_dining_cabinet/scene.gltf')
    return (
        <group scale={[0.03, 0.03, 0.03]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[47.94, 66.23, 24.63]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={nodes.Object_6.material}
                        />
                    </group>
                    <group position={[0.12, 66.21, 24.63]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={nodes.Object_9.material}
                        />
                    </group>
                    <group position={[-47.8, 66.23, 24.63]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={nodes.Object_12.material}
                        />
                    </group>
                    <group position={[-73.73, 58.57, 25.14]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_15.geometry}
                            material={nodes.Object_15.material}
                        />
                    </group>
                    <group position={[73.7, 58.57, 25.14]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_18.geometry}
                            material={nodes.Object_18.material}
                        />
                    </group>
                    <group position={[0.05, 66.25, 24.68]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_21.geometry}
                            material={nodes.Object_21.material}
                        />
                    </group>
                    <group position={[-0.1, 54.88, 0.49]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_24.geometry}
                            material={nodes.Object_24.material}
                        />
                    </group>
                    <group position={[-0.1, 54.17, 0.49]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_27.geometry}
                            material={nodes.Object_27.material}
                        />
                    </group>
                    <group position={[-0.1, 52.95, 0.49]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_30.geometry}
                            material={nodes.Object_30.material}
                        />
                    </group>
                    <group position={[-27.56, 66.52, 26.35]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_33.geometry}
                            material={nodes.Object_33.material}
                        />
                    </group>
                    <group position={[-24.05, 67.52, -0.53]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_36.geometry}
                            material={nodes.Object_36.material}
                        />
                    </group>
                    <group position={[0.13, 85.58, -0.66]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_39.geometry}
                            material={nodes.Object_39.material}
                        />
                    </group>
                    <group position={[0.13, 50.12, -0.8]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_42.geometry}
                            material={nodes.Object_42.material}
                        />
                    </group>
                    <group position={[24.33, 67.49, -0.54]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_45.geometry}
                            material={nodes.Object_45.material}
                        />
                    </group>
                    <group position={[-72.91, 65.88, -0.27]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_48.geometry}
                            material={nodes.Object_48.material}
                        />
                    </group>
                    <group position={[-0.03, 65.88, -25.63]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_51.geometry}
                            material={nodes.Object_51.material}
                        />
                    </group>
                    <group position={[-0.04, 18.36, -0.66]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_54.geometry}
                            material={nodes.Object_54.material}
                        />
                    </group>
                    <group position={[-0.03, 16.83, 24.37]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_57.geometry}
                            material={nodes.Object_57.material}
                        />
                    </group>
                    <group position={[-0.01, 115.11, 24.37]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_60.geometry}
                            material={nodes.Object_60.material}
                        />
                    </group>
                    <group position={[-0.01, 118.67, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_63.geometry}
                            material={nodes.Object_63.material}
                        />
                    </group>
                    <group position={[-0.01, 117.23, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_66.geometry}
                            material={nodes.Object_66.material}
                        />
                    </group>
                    <group position={[72.83, 65.88, -0.27]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_69.geometry}
                            material={nodes.Object_69.material}
                        />
                    </group>
                    <group position={[72.83, 58.41, -25.55]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_72.geometry}
                            material={nodes.Object_72.material}
                        />
                    </group>
                    <group position={[-72.92, 58.41, -25.55]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_75.geometry}
                            material={nodes.Object_75.material}
                        />
                    </group>
                    <group position={[-37.52, 173.05, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_78.geometry}
                            material={nodes.Object_78.material}
                        />
                    </group>
                    <group position={[-37.52, 185.24, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_81.geometry}
                            material={nodes.Object_81.material}
                        />
                    </group>
                    <group position={[-37.52, 183.73, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_84.geometry}
                            material={nodes.Object_84.material}
                        />
                    </group>
                    <group position={[-28.62, 173.17, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_87.geometry}
                            material={nodes.Object_87.material}
                        />
                    </group>
                    <group position={[-37.52, 178.51, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_90.geometry}
                            material={nodes.Object_90.material}
                        />
                    </group>
                    <group position={[-37.51, 167.21, 2.19]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_93.geometry}
                            material={nodes.Object_93.material}
                        />
                    </group>
                    <group position={[-37.5, 163.66, 2.21]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_96.geometry}
                            material={nodes.Object_96.material}
                        />
                    </group>
                    <group position={[-37.52, 162.65, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_99.geometry}
                            material={nodes.Object_99.material}
                        />
                    </group>
                    <group position={[-37.52, 160.41, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_102.geometry}
                            material={nodes.Object_102.material}
                        />
                    </group>
                    <group position={[-37.52, 141.05, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_105.geometry}
                            material={nodes.Object_105.material}
                        />
                    </group>
                    <group position={[-37.52, 122.08, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_108.geometry}
                            material={nodes.Object_108.material}
                        />
                    </group>
                    <group position={[17.83, 120.88, -0.27]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_111.geometry}
                            material={nodes.Object_111.material}
                        />
                    </group>
                    <group position={[-0.32, 8.28, 14.5]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_114.geometry}
                            material={nodes.Object_114.material}
                        />
                    </group>
                    <group position={[41, 8.32, -2.97]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_117.geometry}
                            material={nodes.Object_117.material}
                        />
                    </group>
                    <group position={[-0.04, 8.28, -0.66]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_120.geometry}
                            material={nodes.Object_120.material}
                        />
                    </group>
                    <group position={[-41.66, 8.32, -2.97]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_123.geometry}
                            material={nodes.Object_123.material}
                        />
                    </group>
                    <group position={[0.97, 33.52, 6.5]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_126.geometry}
                            material={nodes.Object_126.material}
                        />
                    </group>
                    <group position={[0.97, 24.75, 6.5]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_129.geometry}
                            material={nodes.Object_129.material}
                        />
                    </group>
                    <group position={[-37.52, 140.51, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_132.geometry}
                            material={nodes.Object_132.material}
                        />
                    </group>
                    <group position={[-37.52, 121.48, -4.05]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_135.geometry}
                            material={nodes.Object_135.material}
                        />
                    </group>
                    <group position={[-37.52, 173.17, -6.7]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_138.geometry}
                            material={nodes.Object_138.material}
                        />
                    </group>
                    <group position={[-46.41, 173.17, 2.2]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_141.geometry}
                            material={nodes.Object_141.material}
                        />
                    </group>
                    <group position={[-37.52, 173.17, 11.09]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_144.geometry}
                            material={nodes.Object_144.material}
                        />
                    </group>
                    <group position={[21.32, 66.52, 26.35]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_147.geometry}
                            material={nodes.Object_147.material}
                        />
                    </group>
                    <group position={[28.01, 66.52, 26.35]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_150.geometry}
                            material={nodes.Object_150.material}
                        />
                    </group>
                    <group position={[-37.58, 166.9, 2.19]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_153.geometry}
                            material={nodes.Object_153.material}
                        />
                    </group>
                    <group position={[-37.52, 166.79, 2.22]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_156.geometry}
                            material={nodes.Object_156.material}
                        />
                    </group>
                    <group position={[13.28, 132.07, -1.12]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_159.geometry}
                            material={nodes.Object_159.material}
                        />
                    </group>
                    <group position={[26.58, 141.15, -0.66]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_162.geometry}
                            material={nodes.Object_162.material}
                        />
                    </group>
                    <group position={[13.27, 136.45, -0.66]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_165.geometry}
                            material={nodes.Object_165.material}
                        />
                    </group>
                    <group position={[26.58, 136.65, -1.12]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_168.geometry}
                            material={nodes.Object_168.material}
                        />
                    </group>
                    <group position={[17.83, 124.37, -0.27]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_171.geometry}
                            material={nodes.Object_171.material}
                        />
                    </group>
                    <group position={[20.85, 129.08, -1.1]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_174.geometry}
                            material={nodes.Object_174.material}
                        />
                    </group>
                    <group position={[0.31, 116.53, -0.54]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_177.geometry}
                            material={nodes.Object_177.material}
                        />
                    </group>
                    <group position={[26.58, 129, -1.1]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_180.geometry}
                            material={nodes.Object_180.material}
                        />
                    </group>
                    <group position={[13.28, 126.79, -1.09]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_183.geometry}
                            material={nodes.Object_183.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/european_style_dining_cabinet/scene.gltf')