/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HippoStance (https://sketchfab.com/hippostance)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dish-rack-with-dishes-ce69014964624fbb808a028e5c55d88b
title: Dish Rack with Dishes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dishes(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/dish_rack_with_dishes/scene.gltf')
    return (
        <group scale={[0.4, 0.4, 0.4]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 0.1]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[1.6, -3.47, 19.95]}>
                        <group position={[0, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.DishRack_DishRack_0.geometry}
                                material={nodes.DishRack_DishRack_0.material}
                            />
                        </group>
                        <group position={[14.01, -9.17, 0.04]} rotation={[-0.7, 0.12, -1.71]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.DishPlateA_DishRack_0.geometry}
                                material={nodes.DishPlateA_DishRack_0.material}
                            />
                        </group>
                        <group position={[10.27, -9.17, 0.04]} rotation={[0.91, -0.17, -1.7]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.DishPlateB_DishRack_0.geometry}
                                material={nodes.DishPlateB_DishRack_0.material}
                            />
                        </group>
                        <group position={[5.77, -9.02, 0.04]} rotation={[0, 0, -1.79]} scale={[1, 1, 1]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.DishPlateC_DishRack_0.geometry}
                                material={nodes.DishPlateC_DishRack_0.material}
                            />
                        </group>
                        <group position={[-3.99, -14.16, -0.02]} rotation={[0, 0, Math.PI]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.DishBowl_DishRack_0.geometry}
                                material={nodes.DishBowl_DishRack_0.material}
                            />
                        </group>
                        <group position={[-12.71, -3.62, -11.86]} rotation={[2.85, 0, 0]} scale={[1, 1, 1]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.DishCup_DishRack_0.geometry}
                                material={nodes.DishCup_DishRack_0.material}
                            />
                        </group>
                        <group position={[-18.97, -4.18, -4.04]} rotation={[1.54, -0.07, -1.03]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.UtensilSpoon_DishRack_0.geometry}
                                material={nodes.UtensilSpoon_DishRack_0.material}
                            />
                        </group>
                        <group position={[-18.47, -7.89, -1.43]} rotation={[Math.PI / 2, 0.14, -Math.PI / 2]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.UtensilKnife_DishRack_0.geometry}
                                material={nodes.UtensilKnife_DishRack_0.material}
                            />
                        </group>
                        <group
                            position={[-14.95, -3.44, 2.72]}
                            rotation={[Math.PI / 2, -0.37, -Math.PI / 2]}
                            scale={[1, 1, 1]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.UtensilForkB_DishRack_0.geometry}
                                material={nodes.UtensilForkB_DishRack_0.material}
                            />
                        </group>
                        <group position={[-14.97, -3.53, -4.43]} rotation={[1.41, -0.11, 0.83]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.UtensilForkA_DishRack_0.geometry}
                                material={nodes.UtensilForkA_DishRack_0.material}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/dish_rack_with_dishes/scene.gltf')