/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pooja_Maurya (https://sketchfab.com/Pooja_Maurya)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/flowervase-dd034b35949f4d0182b576565e54b52b
title: FlowerVase
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function FlowerVase2(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/flowervase/scene.gltf')
    return (
        <group scale={[0.15, 0.15, 0.15]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-5.86, 0, 0]}>
                        <group position={[7.2, 0.8, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.nurbsToPoly1_vase_0.geometry}
                                material={materials.vase}
                            />
                        </group>
                        <group position={[7.2, 0, 0]}>
                            <group
                                position={[-1, 8.45, 0.01]}
                                rotation={[3.13, -0.03, -0.08]}
                                scale={[0.59, 0.59, 0.59]}>
                                <group
                                    position={[0, -12.02, 0]}
                                    rotation={[-1.3, 0.99, -0.26]}
                                    scale={[0.51, 0.51, 0.51]}>
                                    <group
                                        position={[-3.5, -2.05, -0.36]}
                                        rotation={[0.06, -0.11, -1.04]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane9_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane9_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.74, 1.58, -0.36]}
                                        rotation={[-0.05, -0.11, -1.97]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane8_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane8_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-1.44, 3.8, -0.36]}
                                        rotation={[-0.12, -0.04, -2.78]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane7_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane7_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.95, -2.75, -1.18]}
                                        rotation={[0.13, 0.09, 0.81]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane2_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane2_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.5, 2.06, -0.36]}
                                        rotation={[-0.06, 0.11, 2.1]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane6_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane6_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.76, -1.54, -0.36]}
                                        rotation={[0.05, 0.11, 1.18]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane5_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane5_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.22, -3.3, -1.01]}
                                        rotation={[0.24, -0.06, -0.58]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane4_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane4_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[4.07, 0.14, -0.8]}
                                        rotation={[0.03, 0.07, 1.6]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane10_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane10_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[0.03, -4.05, -0.36]}
                                        rotation={[0.12, -0.01, 0.01]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane1_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane1_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.5, -3.8, -0.06]}
                                        rotation={[0, 0, 0.38]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane3_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane3_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.78, -4.01, -0.06]}
                                        rotation={[0, 0, -0.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane17_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane17_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.8, -1.5, -0.06]}
                                        rotation={[0, 0, -1.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane16_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane16_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.63, 3.76, -0.06]}
                                        rotation={[0, 0, 2.73]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane15_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane15_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-4.08, -0.12, -0.79]}
                                        rotation={[-0.03, -0.07, -1.54]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane14_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane14_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.15, 4, -1.37]}
                                        rotation={[-0.21, 0.03, -3.11]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane12_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane12_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.98, 2.8, -0.88]}
                                        rotation={[-0.07, -0.03, -2.33]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane13_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane13_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.79, 2.98, -0.73]}
                                        rotation={[-0.03, 0.07, 2.39]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane11_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane11_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.77, 1.21, -0.08]}
                                        rotation={[-3.12, -0.01, 1.26]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane18_flowerpetelMT_0.geometry}
                                            material={nodes.pPlane18_flowerpetelMT_0.material}
                                        />
                                    </group>
                                    <group position={[0.03, -0.2, -0.38]} rotation={[Math.PI / 2, 0, 0]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pTorus2_stemenFlowerMt_0.geometry}
                                            material={nodes.pTorus2_stemenFlowerMt_0.material}
                                        />
                                    </group>
                                </group>
                                <group
                                    position={[0.45, -11.83, 0.16]}
                                    rotation={[0.33, 0.13, 2.15]}
                                    scale={[0.67, 0.67, 0.67]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCone1_partofStemMT_0.geometry}
                                        material={nodes.pCone1_partofStemMT_0.material}
                                    />
                                </group>
                                <group
                                    position={[1.11, -4.72, 0.07]}
                                    rotation={[0, 0, 0]}
                                    scale={[0.32, 0.6, 0.32]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCylinder1_flowerStemMt_0.geometry}
                                        material={nodes.pCylinder1_flowerStemMt_0.material}
                                    />
                                </group>
                            </group>
                            <group
                                position={[0.44, 7.65, 0.07]}
                                rotation={[-0.04, -0.1, 2.95]}
                                scale={[0.59, 0.59, 0.59]}>
                                <group
                                    position={[0, -12.02, 0]}
                                    rotation={[-1.3, 0.99, -0.26]}
                                    scale={[0.43, 0.43, 0.43]}>
                                    <group
                                        position={[-3.5, -2.05, -0.36]}
                                        rotation={[0.06, -0.11, -1.04]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane9_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane9_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.74, 1.58, -0.36]}
                                        rotation={[-0.05, -0.11, -1.97]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane8_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane8_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-1.44, 3.8, -0.36]}
                                        rotation={[-0.12, -0.04, -2.78]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane7_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane7_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.95, -2.75, -1.18]}
                                        rotation={[0.13, 0.09, 0.81]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane2_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane2_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.5, 2.06, -0.36]}
                                        rotation={[-0.06, 0.11, 2.1]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane6_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane6_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.76, -1.54, -0.36]}
                                        rotation={[0.05, 0.11, 1.18]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane5_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane5_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.22, -3.3, -1.01]}
                                        rotation={[0.24, -0.06, -0.58]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane4_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane4_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[4.07, 0.14, -0.8]}
                                        rotation={[0.03, 0.07, 1.6]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane10_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane10_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group position={[0.01, -0.14, -0.41]} rotation={[Math.PI / 2, 0, 0]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pTorus1_stemenFlowerMt_0.geometry}
                                            material={nodes.pTorus1_stemenFlowerMt_0.material}
                                        />
                                    </group>
                                    <group
                                        position={[0.03, -4.05, -0.36]}
                                        rotation={[0.12, -0.01, 0.01]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane1_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane1_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.5, -3.8, -0.06]}
                                        rotation={[0, 0, 0.38]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane3_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane3_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.78, -4.01, -0.06]}
                                        rotation={[0, 0, -0.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane17_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane17_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.8, -1.5, -0.06]}
                                        rotation={[0, 0, -1.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane16_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane16_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.63, 3.76, -0.06]}
                                        rotation={[0, 0, 2.73]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane15_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane15_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-4.08, -0.12, -0.79]}
                                        rotation={[-0.03, -0.07, -1.54]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane14_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane14_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.15, 4, -1.37]}
                                        rotation={[-0.21, 0.03, -3.11]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane12_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane12_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.98, 2.8, -0.88]}
                                        rotation={[-0.07, -0.03, -2.33]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane13_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane13_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.79, 2.98, -0.73]}
                                        rotation={[-0.03, 0.07, 2.39]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane11_flowerpetelMT_0_1.geometry}
                                            material={nodes.pPlane11_flowerpetelMT_0_1.material}
                                        />
                                    </group>
                                </group>
                                <group
                                    position={[0.48, -11.82, 0.03]}
                                    rotation={[0.33, 0.13, 2.15]}
                                    scale={[0.67, 0.67, 0.67]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCone1_partofStemMT_0_1.geometry}
                                        material={nodes.pCone1_partofStemMT_0_1.material}
                                    />
                                </group>
                                <group
                                    position={[1.11, -4.72, 0.07]}
                                    rotation={[0, 0, 0]}
                                    scale={[0.32, 0.6, 0.32]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCylinder2_flowerStemMt_0.geometry}
                                        material={nodes.pCylinder2_flowerStemMt_0.material}
                                    />
                                </group>
                            </group>
                            <group
                                position={[0.4, 9.68, 0.78]}
                                rotation={[0.88, -1.32, -2.48]}
                                scale={[0.59, 0.59, 0.59]}>
                                <group
                                    position={[0, -12.02, 0]}
                                    rotation={[-1.3, 0.99, -0.26]}
                                    scale={[0.5, 0.5, 0.5]}>
                                    <group
                                        position={[-3.5, -2.05, -0.36]}
                                        rotation={[0.06, -0.11, -1.04]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane9_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane9_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.74, 1.58, -0.36]}
                                        rotation={[-0.05, -0.11, -1.97]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane8_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane8_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-1.44, 3.8, -0.36]}
                                        rotation={[-0.12, -0.04, -2.78]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane7_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane7_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.95, -2.75, -1.18]}
                                        rotation={[0.13, 0.09, 0.81]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane2_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane2_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.5, 2.06, -0.36]}
                                        rotation={[-0.06, 0.11, 2.1]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane6_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane6_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.76, -1.54, -0.36]}
                                        rotation={[0.05, 0.11, 1.18]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane5_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane5_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.22, -3.3, -1.01]}
                                        rotation={[0.24, -0.06, -0.58]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane4_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane4_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[4.07, 0.14, -0.8]}
                                        rotation={[0.03, 0.07, 1.6]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane10_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane10_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[0.03, -4.05, -0.36]}
                                        rotation={[0.12, -0.01, 0.01]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane1_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane1_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.5, -3.8, -0.06]}
                                        rotation={[0, 0, 0.38]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane3_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane3_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.78, -4.01, -0.06]}
                                        rotation={[0, 0, -0.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane17_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane17_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.8, -1.5, -0.06]}
                                        rotation={[0, 0, -1.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane16_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane16_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.63, 3.76, -0.06]}
                                        rotation={[0, 0, 2.73]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane15_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane15_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-4.08, -0.12, -0.79]}
                                        rotation={[-0.03, -0.07, -1.54]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane14_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane14_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.15, 4, -1.37]}
                                        rotation={[-0.21, 0.03, -3.11]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane12_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane12_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.98, 2.8, -0.88]}
                                        rotation={[-0.07, -0.03, -2.33]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane13_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane13_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.79, 2.98, -0.73]}
                                        rotation={[-0.03, 0.07, 2.39]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane11_flowerpetelMT_0_2.geometry}
                                            material={nodes.pPlane11_flowerpetelMT_0_2.material}
                                        />
                                    </group>
                                    <group position={[0.01, 0.05, -0.43]} rotation={[Math.PI / 2, 0, 0]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pTorus2_stemenFlowerMt_0_1.geometry}
                                            material={nodes.pTorus2_stemenFlowerMt_0_1.material}
                                        />
                                    </group>
                                </group>
                                <group
                                    position={[0.48, -11.82, 0.03]}
                                    rotation={[0.33, 0.13, 2.15]}
                                    scale={[0.67, 0.67, 0.67]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCone1_partofStemMT_0_2.geometry}
                                        material={nodes.pCone1_partofStemMT_0_2.material}
                                    />
                                </group>
                                <group
                                    position={[1.11, -4.72, 0.07]}
                                    rotation={[0, 0, 0]}
                                    scale={[0.32, 0.6, 0.32]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCylinder2_flowerStemMt_0_1.geometry}
                                        material={nodes.pCylinder2_flowerStemMt_0_1.material}
                                    />
                                </group>
                            </group>
                            <group
                                position={[-0.01, 9.38, -1.05]}
                                rotation={[0.66, 1.5, 2.35]}
                                scale={[0.59, 0.59, 0.59]}>
                                <group
                                    position={[0, -12.02, 0]}
                                    rotation={[-1.3, 0.99, -0.26]}
                                    scale={[0.39, 0.39, 0.39]}>
                                    <group
                                        position={[-3.5, -2.05, -0.36]}
                                        rotation={[0.06, -0.11, -1.04]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane9_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane9_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.74, 1.58, -0.36]}
                                        rotation={[-0.05, -0.11, -1.97]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane8_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane8_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-1.44, 3.8, -0.36]}
                                        rotation={[-0.12, -0.04, -2.78]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane7_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane7_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.95, -2.75, -1.18]}
                                        rotation={[0.13, 0.09, 0.81]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane2_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane2_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.5, 2.06, -0.36]}
                                        rotation={[-0.06, 0.11, 2.1]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane6_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane6_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.76, -1.54, -0.36]}
                                        rotation={[0.05, 0.11, 1.18]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane5_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane5_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.22, -3.3, -1.01]}
                                        rotation={[0.24, -0.06, -0.58]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane4_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane4_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[4.07, 0.14, -0.8]}
                                        rotation={[0.03, 0.07, 1.6]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane10_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane10_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[0.03, -4.05, -0.36]}
                                        rotation={[0.12, -0.01, 0.01]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane1_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane1_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.5, -3.8, -0.06]}
                                        rotation={[0, 0, 0.38]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane3_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane3_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.78, -4.01, -0.06]}
                                        rotation={[0, 0, -0.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane17_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane17_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.8, -1.5, -0.06]}
                                        rotation={[0, 0, -1.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane16_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane16_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.63, 3.76, -0.06]}
                                        rotation={[0, 0, 2.73]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane15_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane15_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-4.08, -0.12, -0.79]}
                                        rotation={[-0.03, -0.07, -1.54]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane14_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane14_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.15, 4, -1.37]}
                                        rotation={[-0.21, 0.03, -3.11]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane12_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane12_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.98, 2.8, -0.88]}
                                        rotation={[-0.07, -0.03, -2.33]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane13_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane13_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.79, 2.98, -0.73]}
                                        rotation={[-0.03, 0.07, 2.39]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane11_flowerpetelMT_0_3.geometry}
                                            material={nodes.pPlane11_flowerpetelMT_0_3.material}
                                        />
                                    </group>
                                    <group position={[0.03, -0.2, -0.4]} rotation={[Math.PI / 2, 0, 0]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pTorus2_stemenFlowerMt_0_2.geometry}
                                            material={nodes.pTorus2_stemenFlowerMt_0_2.material}
                                        />
                                    </group>
                                </group>
                                <group
                                    position={[0.48, -11.82, 0.07]}
                                    rotation={[0.33, 0.13, 2.15]}
                                    scale={[0.67, 0.67, 0.67]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCone1_partofStemMT_0_3.geometry}
                                        material={nodes.pCone1_partofStemMT_0_3.material}
                                    />
                                </group>
                                <group
                                    position={[1.11, -4.72, 0.07]}
                                    rotation={[0, 0, 0]}
                                    scale={[0.32, 0.6, 0.32]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCylinder1_flowerStemMt_0_1.geometry}
                                        material={nodes.pCylinder1_flowerStemMt_0_1.material}
                                    />
                                </group>
                            </group>
                            <group
                                position={[0.38, 11.33, -0.28]}
                                rotation={[0.07, 0.37, 3.14]}
                                scale={[0.59, 0.59, 0.59]}>
                                <group
                                    position={[0, -12.02, 0]}
                                    rotation={[-1.36, 0.82, -0.21]}
                                    scale={[0.41, 0.41, 0.41]}>
                                    <group
                                        position={[-3.5, -2.05, -0.36]}
                                        rotation={[0.06, -0.11, -1.04]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane9_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane9_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.74, 1.58, -0.36]}
                                        rotation={[-0.05, -0.11, -1.97]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane8_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane8_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-1.44, 3.8, -0.36]}
                                        rotation={[-0.12, -0.04, -2.78]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane7_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane7_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.95, -2.75, -1.18]}
                                        rotation={[0.13, 0.09, 0.81]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane2_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane2_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.5, 2.06, -0.36]}
                                        rotation={[-0.06, 0.11, 2.1]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane6_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane6_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[3.76, -1.54, -0.36]}
                                        rotation={[0.05, 0.11, 1.18]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane5_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane5_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.22, -3.3, -1.01]}
                                        rotation={[0.24, -0.06, -0.58]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane4_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane4_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[4.07, 0.14, -0.8]}
                                        rotation={[0.03, 0.07, 1.6]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane10_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane10_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group position={[-0.11, -0.02, -0.36]} rotation={[Math.PI / 2, 0, 0]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pTorus1_stemenFlowerMt_0_1.geometry}
                                            material={nodes.pTorus1_stemenFlowerMt_0_1.material}
                                        />
                                    </group>
                                    <group
                                        position={[0.03, -4.05, -0.36]}
                                        rotation={[0.12, -0.01, 0.01]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane1_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane1_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.5, -3.8, -0.06]}
                                        rotation={[0, 0, 0.38]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane3_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane3_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.78, -4.01, -0.06]}
                                        rotation={[0, 0, -0.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane17_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane17_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-3.8, -1.5, -0.06]}
                                        rotation={[0, 0, -1.19]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane16_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane16_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[1.63, 3.76, -0.06]}
                                        rotation={[0, 0, 2.73]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane15_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane15_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-4.08, -0.12, -0.79]}
                                        rotation={[-0.03, -0.07, -1.54]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane14_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane14_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-0.15, 4, -1.37]}
                                        rotation={[-0.21, 0.03, -3.11]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane12_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane12_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[-2.98, 2.8, -0.88]}
                                        rotation={[-0.07, -0.03, -2.33]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane13_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane13_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                    <group
                                        position={[2.79, 2.98, -0.73]}
                                        rotation={[-0.03, 0.07, 2.39]}
                                        scale={[0.3, 0.37, 0.37]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.pPlane11_flowerpetelMT_0_4.geometry}
                                            material={nodes.pPlane11_flowerpetelMT_0_4.material}
                                        />
                                    </group>
                                </group>
                                <group
                                    position={[0.48, -11.82, 0.03]}
                                    rotation={[0.33, 0.13, 2.15]}
                                    scale={[0.67, 0.67, 0.67]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCone1_partofStemMT_0_4.geometry}
                                        material={nodes.pCone1_partofStemMT_0_4.material}
                                    />
                                </group>
                                <group
                                    position={[1.11, -4.72, 0.07]}
                                    rotation={[0, 0, 0]}
                                    scale={[0.32, 0.6, 0.32]}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.pCylinder1_flowerStemMt_0_2.geometry}
                                        material={nodes.pCylinder1_flowerStemMt_0_2.material}
                                    />
                                </group>
                            </group>
                        </group>
                        <group
                            position={[7.25, 8.72, -1.29]}
                            rotation={[1.61, 0, -0.14]}
                            scale={[0.22, 0.16, 0.48]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pPlane47_leafMt_0.geometry}
                                material={nodes.pPlane47_leafMt_0.material}
                            />
                        </group>
                        <group
                            position={[6.08, 11.59, 1.02]}
                            rotation={[1.7, 0.12, -2.57]}
                            scale={[0.15, 0.11, 0.32]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pPlane48_leafMt_0.geometry}
                                material={nodes.pPlane48_leafMt_0.material}
                            />
                        </group>
                        <group
                            position={[8.28, 10.93, -1.46]}
                            rotation={[1.52, -0.02, 0.63]}
                            scale={[0.13, 0.16, 0.4]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pPlane49_leafMt_0.geometry}
                                material={nodes.pPlane49_leafMt_0.material}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/flowervase/scene.gltf')