/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 9arts (https://sketchfab.com/9arts)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gaming-chair-6ca81f60846648609b4208c9e7f31b14
title: Gaming Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GameChair(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/gaming_chair/scene.gltf')
    return (
        <group scale={[0.001, 0.001, 0.001]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[1877.52, 4423.41, 8562.79]}
                        rotation={[3.14, 1.37, 2.94]}
                        scale={[573.16, 573.16, 573.16]}
                    />
                    <group
                        position={[45.83, 5015.84, 9400.27]}
                        rotation={[-0.26, Math.PI / 2, 0]}
                        scale={[221.04, 221.04, 221.04]}
                    />
                    <group
                        position={[-19.55, 8847.45, 69.96]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={[496.54, 496.54, 496.54]}
                    />
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh1_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh1_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh2_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh2_skp7AF7_1_Model__auto__0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh2_skp7AF7_1_Model__auto_1_0.geometry}
                            material={nodes.Mesh2_skp7AF7_1_Model__auto_1_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh3_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh3_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh4_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh4_skp7AF7_1_Model__auto__0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh4_skp7AF7_1_Model__auto_1_0.geometry}
                            material={nodes.Mesh4_skp7AF7_1_Model__auto_1_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh5_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh5_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh6_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh6_skp7AF7_1_Model__auto__0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh6_skp7AF7_1_Model__auto_1_0.geometry}
                            material={nodes.Mesh6_skp7AF7_1_Model__auto_1_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh7_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh7_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh8_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh8_skp7AF7_1_Model__auto__0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh8_skp7AF7_1_Model__auto_1_0.geometry}
                            material={nodes.Mesh8_skp7AF7_1_Model__auto_1_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh9_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh9_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh10_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh10_skp7AF7_1_Model__auto__0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh10_skp7AF7_1_Model__auto_1_0.geometry}
                            material={nodes.Mesh10_skp7AF7_1_Model__auto_1_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh11_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh11_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh12_skp7AF7_1_Model__auto_3_0.geometry}
                            material={nodes.Mesh12_skp7AF7_1_Model__auto_3_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh13_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh13_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh14_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh14_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh15_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh15_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh16_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh16_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh17_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh17_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh18_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh18_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh19_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh19_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh20_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh20_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh21_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh21_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh22_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh22_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh23_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh23_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh24_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh24_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh25_skp7AF7_1_Model__auto_3_0.geometry}
                            material={nodes.Mesh25_skp7AF7_1_Model__auto_3_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh26_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh26_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh27_skp7AF7_1_Model__auto_3_0.geometry}
                            material={nodes.Mesh27_skp7AF7_1_Model__auto_3_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh28_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh28_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh29_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh29_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh30_skp7AF7_1_Model__auto_4_0.geometry}
                            material={nodes.Mesh30_skp7AF7_1_Model__auto_4_0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh30_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh30_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh31_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh31_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh32_skp7AF7_1_Model__auto_4_0.geometry}
                            material={nodes.Mesh32_skp7AF7_1_Model__auto_4_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh33_skp7AF7_1_Model__auto_4_0.geometry}
                            material={nodes.Mesh33_skp7AF7_1_Model__auto_4_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh34_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh34_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh35_skp7AF7_1_Model__auto_4_0.geometry}
                            material={nodes.Mesh35_skp7AF7_1_Model__auto_4_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh36_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh36_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh37_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh37_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh38_skp7AF7_1_Model__auto_3_0.geometry}
                            material={nodes.Mesh38_skp7AF7_1_Model__auto_3_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh39_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh39_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh40_skp7AF7_1_Model__auto_4_0.geometry}
                            material={nodes.Mesh40_skp7AF7_1_Model__auto_4_0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh40_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh40_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh41_skp7AF7_1_Model__auto_4_0.geometry}
                            material={nodes.Mesh41_skp7AF7_1_Model__auto_4_0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh41_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh41_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh42_skp7AF7_1_Model__auto_6_0.geometry}
                            material={materials.auto_6}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh43_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh43_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh44_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh44_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh45_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh45_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh46_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh46_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh47_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh47_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh50_skp7AF7_1_Model__auto_5001_0.geometry}
                            material={nodes.Mesh50_skp7AF7_1_Model__auto_5001_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh51_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh51_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh52_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh52_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh53_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh53_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh54_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh54_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh55_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh55_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh56_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh56_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh57_skp7AF7_1_Model_Plastic_Black_Matte_0.geometry}
                            material={nodes.Mesh57_skp7AF7_1_Model_Plastic_Black_Matte_0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh58_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh58_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh59_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh59_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh60_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh60_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh61_skp7AF7_1_Model__auto__0.geometry}
                            material={nodes.Mesh61_skp7AF7_1_Model__auto__0.material}
                        />
                    </group>
                    <group rotation={[0, 0, 0]} scale={[100, 100, 100]}>
                        <group rotation={[Math.PI / 2, 0, 0]} />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/gaming_chair/scene.gltf')