/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benji Labs (https://sketchfab.com/benjilabs)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-imac-m1-silver-7c60798464fd47698689038f5587aafa
title: Apple iMac M1 (Silver)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Imac(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/apple_imac_m1_silver/scene.gltf')
    return (
        <group scale={[4, 4, 4]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
                    <group
                        position={[5.49, -0.11, -17.24]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[102.87, 102.87, 102.87]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.iMac_Silver_iMac_Grey_Shader_0.geometry}
                            material={materials.iMac_Grey_Shader}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.iMac_Silver_iMac_Screen_0.geometry}
                            material={materials.iMac_Screen}
                        />
                    </group>
                    <group
                        position={[22.33, 0.49, 13.06]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Trackpad_iMac_White_Glass001_0.geometry}
                            material={materials['iMac_White_Glass.001']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Trackpad_iMac_Grey_Aluminium_0.geometry}
                            material={nodes.Trackpad_iMac_Grey_Aluminium_0.material}
                        />
                    </group>
                    <group
                        position={[-5.19, 1.18, 12.81]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Keyboard_iMac_White_Glass_0.geometry}
                            material={materials.iMac_White_Glass}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Keyboard_iMac_Grey_Aluminium_0.geometry}
                            material={nodes.Keyboard_iMac_Grey_Aluminium_0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Keyboard_Keyboard_Keys_0.geometry}
                            material={materials.Keyboard_Keys}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/apple_imac_m1_silver/scene.gltf')