/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hako (https://sketchfab.com/hako25AI)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/indoor-plant-0c1e8c7de0d9477787d8d7c482a10342
title: Indoor Plant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function IndoorPlant(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/indoor_plant/scene.gltf')
    return (
        <group scale={[0.4, 0.4, 0.4]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <primitive object={nodes._rootJoint} />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_5.geometry}
                        material={materials.plant}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_6.geometry}
                        material={materials.Leaf2}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/indoor_plant/scene.gltf')