/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniyal Malik (https://sketchfab.com/daniyalmalik)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/led-tv-014e75456b4e465b9cecd1b136a0312b
title: Led Tv
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LedTV(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/led_tv/scene.gltf')
    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.3, 0.3, 0.3]}>
                    <group position={[0.57, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.led_tv_phong1_0.geometry}
                            material={materials.phong1}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/led_tv/scene.gltf')