/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Whystler (https://sketchfab.com/Whystler)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/mars-poster-fe37ea9b8bdd4debab6605facd087bc4
title: Mars Poster
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MarsPoster(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/mars_poster/scene.gltf')
    return (
        <group scale={[0.04, 0.04, 0.04]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.material_frame}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.material_matting}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={materials.material_poster}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/mars_poster/scene.gltf')