/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zuo Modern (https://sketchfab.com/zuo)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/round-mirror-black-a10321-017708fc9a0940a99eeead19664648c8
title: Round Mirror Black - A10321
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mirror(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/round_mirror_black_-_a10321/scene.gltf')
    return (
        <group scale={[0.005, 0.005, 0.005]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[35.23, 0.47, -4.29]} rotation={[-Math.PI / 2, 0, 0]}>
                        <group position={[-35.23, -4.29, -0.47]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object001_Object001_mtl_0.geometry}
                                material={materials.Object001_mtl}
                            />
                        </group>
                    </group>
                    <group position={[35.23, 0.47, -4.29]} rotation={[-Math.PI / 2, 0, 0]}>
                        <group position={[-35.23, -4.29, -0.47]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object002_Object002_mtl_0.geometry}
                                material={nodes.Object002_Object002_mtl_0.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object002_Object002_mtl_0_1.geometry}
                                material={nodes.Object002_Object002_mtl_0_1.material}
                            />
                        </group>
                    </group>
                    <group position={[35.23, 0.47, -4.29]} rotation={[-Math.PI / 2, 0, 0]}>
                        <group position={[-35.23, -4.29, -0.47]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object003_Object003_mtl_0.geometry}
                                material={nodes.Object003_Object003_mtl_0.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object003_Object003_mtl_0_1.geometry}
                                material={nodes.Object003_Object003_mtl_0_1.material}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/round_mirror_black_-_a10321/scene.gltf')
