/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: samplemem (https://sketchfab.com/duts2024)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nike-shoe-box-6eb4190c3ca847c8853226c90d1ea37a
title: Nike Shoe Box
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Nike(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/nike_shoe_box/scene.gltf')
    const { actions } = useAnimations(animations, group)
    return (
        <group scale={[3.3, 3.3, 3.3]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[1.52, 1.52, 1.52]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
                    <group position={[0, 0.05, 0]}>
                        <group position={[0, 11.55, -9.86]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane_Plane_002_Material_001_TOP_0.geometry}
                                material={materials.material}
                            />
                        </group>
                        <group position={[0, 0.05, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane_Plane_002_carton_BOTTOM_0.geometry}
                                material={materials.BOTTOM}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/nike_shoe_box/scene.gltf')