/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Digitalis Reality (https://sketchfab.com/digitalisreality)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-nintendo-switch-dd11aad5f79b4b26a18f59095082a242
title: Low Poly Nintendo Switch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Nintendo(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/low_poly_nintendo_switch/scene.gltf')
    return (
        <group scale={[0.01, 0.01, 0.01]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, -0.3]} scale={[8.35, 8.35, 8.35]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials.switch_body}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5.geometry}
                            material={materials.switch_joycon_R}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials.switch_buttons}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_7.geometry}
                            material={materials.switch_joycon_L}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_8.geometry}
                            material={materials.screen}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/low_poly_nintendo_switch/scene.gltf')