/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jamesaalam (https://sketchfab.com/Jamesaalam)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/photo-frame-152996ef38f3433c8d80f43531378c4f
title: Photo Frame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Photoframe2(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/photo_frame/scene.gltf')
    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.material_0}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/photo_frame/scene.gltf')
