/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benji Labs (https://sketchfab.com/benjilabs)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylised-large-house-plant-73068e8f47c049ea953c1aea9b317a02
title: Stylised Large House Plant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Plant(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/stylised_large_house_plant/scene.gltf')
    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={[0.04, 0.04, 0.04]}>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={[63.91, 63.91, 63.91]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Large_Plant001_Plant_Leaf_Shader_0.geometry}
                            material={materials.Plant_Leaf_Shader}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Large_Plant001_Pot_Shader_0.geometry}
                            material={materials.Pot_Shader}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/stylised_large_house_plant/scene.gltf')