/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: POSTOBOY (https://sketchfab.com/johnthyque)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hip-poster-prince-256d067e442a4e639fa3b5dce41fa146
title: Hip Poster PRINCE
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Poster1(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/hip_poster_prince/scene.gltf')
    return (
        <group scale={[5, 5, 5]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_4.geometry}
                        material={materials.Material}
                    />
                    <group position={[0.65, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials['Material.001']}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_8.geometry}
                        material={materials['Material.002']}
                    />
                    <group position={[-0.67, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_10.geometry}
                            material={materials['Material.003']}
                        />
                    </group>
                    <group position={[-0.67, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={materials['Material.004']}
                        />
                    </group>
                    <group position={[0.65, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_14.geometry}
                            material={materials['Material.005']}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/hip_poster_prince/scene.gltf')