/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: comphonia (https://sketchfab.com/comphonia)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/projector-set-18428ceaffee47f5b9e90219adbfbefd
title: Projector Set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Projector(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/projector_set/scene.gltf')
    return (
        <group scale={[0.04, 0.04, 0.04]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[0, 0, 0]}>
                        <group position={[4.87, 137.27, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes['Projector_Screen_Material_#27_0'].geometry}
                                material={materials.Material_27}
                            />
                        </group>
                    </group>
                    <group
                        position={[-22.89, 0, 40.3]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[0.89, 0.93, 0.87]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Projector_Projector_0.geometry}
                            material={materials.Projector}
                        />
                    </group>
                    <group position={[17.6, 0, 35.12]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Remote_Projector_0.geometry}
                            material={materials.Projector_0}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/projector_set/scene.gltf')