/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: martin.constable (https://sketchfab.com/martin.constable)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rug-4d58e0e3adad4e37859e35885283184a
title: Rug
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rug(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/rug/scene.gltf')
    return (
        <group scale={[1, 2, 2.5]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-0.12, 0.01, -0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials['Rug.001']}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/rug/scene.gltf')