/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mfb64 (https://sketchfab.com/mfb64)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/striped-persian-jajim-kilim-7259d3abda3c4a0c89bf46995d54f1ee
title: Striped Persian Jajim Kilim
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rug2(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/striped_persian_jajim_kilim/scene.gltf')
    return (
        <group scale={[5, 5, 5]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-0.52, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={nodes.Object_6.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_7.geometry}
                            material={nodes.Object_7.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_8.geometry}
                            material={nodes.Object_8.material}
                        />
                    </group>
                    <group position={[0.5, 0, 0.01]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_10.geometry}
                            material={nodes.Object_10.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_11.geometry}
                            material={nodes.Object_11.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={nodes.Object_12.material}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_4.geometry}
                        material={materials.kilim}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/striped_persian_jajim_kilim/scene.gltf')