/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mfb64 (https://sketchfab.com/mfb64)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bhadoi-rug-b7274481dcfa4290964cd6e509e51952
title: Bhadoi Rug
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rug3(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/bhadoi_rug/scene.gltf')
    return (
        <group scale={[0.3, 0.3, 0.3]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group scale={[0.01, 0.01, 0.01]}>
                        <group scale={[1000, 1000, 1000]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_5.geometry}
                                material={materials.carpet}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_6.geometry}
                                material={materials['carpet.back']}
                            />
                        </group>
                        <group scale={[1000, 1000, 1000]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_8.geometry}
                                material={nodes.Object_8.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_9.geometry}
                                material={nodes.Object_9.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_10.geometry}
                                material={nodes.Object_10.material}
                            />
                        </group>
                        <group scale={[1000, 1000, 1000]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_12.geometry}
                                material={nodes.Object_12.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_13.geometry}
                                material={nodes.Object_13.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_14.geometry}
                                material={nodes.Object_14.material}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/bhadoi_rug/scene.gltf')