/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BlackCube (https://sketchfab.com/blackcube4)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bruno-banani-hair-and-body-shower-shampoo-58a02d153ab347419a303b4421746baf
title: Bruno Banani Hair and Body Shower / Shampoo
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Shampoo(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(
        '/models/bruno_banani_hair_and_body_shower__shampoo/scene.gltf'
    )
    const { actions } = useAnimations(animations, group)
    return (
        <group scale={[0.3, 0.3, 0.3]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.21, 0.21, 0.21]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, 8.06, -1.71]} rotation={[2.89, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Cap_Cap_0.geometry}
                            material={materials.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Cap_Smooth_Plastic_0.geometry}
                            material={nodes.Bruno_Banani_High_Cap_Smooth_Plastic_0.material}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Bottom_0.geometry}
                            material={materials.Bottom}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Smooth_Plastic_0.geometry}
                            material={nodes.Bruno_Banani_High_Smooth_Plastic_0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Sides_0.geometry}
                            material={materials.Sides}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Back_0.geometry}
                            material={materials.Back}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Front_0.geometry}
                            material={materials.Front}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Cap_2_Smooth_Plastic_0.geometry}
                            material={nodes.Bruno_Banani_High_Cap_2_Smooth_Plastic_0.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Cap_2_Cap_2_0.geometry}
                            material={materials.Cap_2}
                        />
                    </group>
                    <group position={[0, 8.06, -1.7]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Cap_Connection_Smooth_Plastic_0.geometry}
                            material={nodes.Bruno_Banani_High_Cap_Connection_Smooth_Plastic_0.material}
                        />
                    </group>
                    <group position={[-0.97, 8.06, -1.64]} rotation={[-Math.PI / 2, 0, 0.11]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bruno_Banani_High_Cap_Connection_2_Smooth_Plastic_0.geometry}
                            material={nodes.Bruno_Banani_High_Cap_Connection_2_Smooth_Plastic_0.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/bruno_banani_hair_and_body_shower__shampoo/scene.gltf')