/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: plaggy (https://sketchfab.com/plaggy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cc0-shelf-3-8038ef78b52d4b528abbe924d07f9e91
title: CC0 - Shelf 3
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shelves(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/cc0_-_shelf_3/scene.gltf')
    return (
        <group scale={[5, 5, 5]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={[0.03, 0.03, 0.03]}>
                    <group rotation={[0, 0, 0]}>
                        <group position={[0, -11.91, -6]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Shelf3_Shelf3_0.geometry}
                                material={materials.Shelf3}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/cc0_-_shelf_3/scene.gltf')