/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Phobos (https://sketchfab.com/1majaxed)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/shoes-8202cb5fdf654563aa6e3d8e188a17d1
title: Shoes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shoes(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/shoes/scene.gltf')
    return (
        <group scale={[0.15, 0.15, 0.15]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.lambert1.geometry}
                        material={materials.lambert1}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/shoes/scene.gltf')