/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: PatelDev (https://sketchfab.com/PatelDev)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sofa-chair-0e8e009f398249b9bc13e8ff7078530a
title: Sofa Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SofaChair(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/sofa_chair/scene.gltf')
    return (
        <group scale={[2, 2, 2]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_4.geometry}
                        material={nodes.Object_4.material}
                    />
                    <group scale={[0.93, 0.99, 0.99]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={nodes.Object_6.material}
                        />
                    </group>
                    <group position={[0, 0.23, 0.04]} scale={[0.86, 1.02, 0.91]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_8.geometry}
                            material={nodes.Object_8.material}
                        />
                    </group>
                    <group position={[0, 0.02, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_10.geometry}
                            material={materials['Material.002']}
                        />
                    </group>
                    <group
                        position={[0.01, 0.68, -0.48]}
                        rotation={[1.24, -0.01, -0.1]}
                        scale={[0.4, 0.29, 0.35]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={materials.material_0}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/sofa_chair/scene.gltf')