/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Glitch5970 (https://sketchfab.com/Glitch5970)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ketchup-mayo-salt-pepper-fnaf-e8d78a8d1a5e4d6e95570a2c64e7120b
title: Ketchup , Mayo & Salt , Pepper - FNaF
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Souce(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/ketchup__mayo__salt__pepper_-_fnaf/scene.gltf')
    return (
        <group scale={[0.005, 0.005, 0.005]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[100, 0, -100]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[39.22, 39.22, 39.22]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mayo__0.geometry}
                            material={nodes.Mayo__0.material}
                        />
                    </group>
                    <group
                        position={[0, 0, 100]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[39.22, 39.22, 39.22]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Ketchup__0.geometry}
                            material={nodes.Ketchup__0.material}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Pepper__0.geometry}
                            material={nodes.Pepper__0.material}
                        />
                    </group>
                    <group
                        position={[0, 128.47, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[22.57, 22.57, 11.95]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Top__0.geometry}
                            material={nodes.Top__0.material}
                        />
                    </group>
                    <group position={[100, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Salt__0.geometry}
                            material={nodes.Salt__0.material}
                        />
                    </group>
                    <group
                        position={[100, 128.47, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[22.57, 22.57, 11.95]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Top001__0.geometry}
                            material={nodes.Top001__0.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/ketchup__mayo__salt__pepper_-_fnaf/scene.gltf')