/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Glowbox 3D (https://sketchfab.com/ra3id)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vintage-stereo-hi-fi-stack-w-speakers-31f5862ac47b436f8db70f8aa47d2b07
title: Vintage Stereo Hi-Fi Stack w/ Speakers
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Speakers(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/vintage_stereo_hi-fi_stack_w_speakers/scene.gltf')
    return (
        <group scale={[0.015, 0.015, 0.015]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.26, 0.26, 0.26]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[34.05, 347.3, 137.66]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Stereo_SM_Material014_0.geometry}
                            material={materials['Material.014']}
                        />
                    </group>
                    <group
                        position={[626, 853.7, 548.79]}
                        rotation={[Math.PI, 0.76, 2.68]}
                        scale={[100, 100, 100]}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/vintage_stereo_hi-fi_stack_w_speakers/scene.gltf')