/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benji Labs (https://sketchfab.com/benjilabs)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/home-office-desk-oak-f5edd5998d934268935de5cdeb310b00
title: Home Office Desk (Oak)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tablee(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/home_office_desk_oak/scene.gltf')
    return (
        <group scale={[3, 3, 3]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
                    <group
                        position={[65.31, -1.22, -82.02]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Desk_#2_Metal_Black_0'].geometry}
                            material={materials.Metal_Black}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Desk_#2_Desk_Oak_0'].geometry}
                            material={nodes['Desk_#2_Desk_Oak_0'].material}
                        />
                    </group>
                    <group
                        position={[-0.05, 70.16, -103.05]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[44.24, 9.05, 1.41]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Monitor_Riser_Desk_Black_0.geometry}
                            material={materials.Desk_Black}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Monitor_Riser_Desk_Oak_0.geometry}
                            material={nodes.Monitor_Riser_Desk_Oak_0.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/home_office_desk_oak/scene.gltf')