/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: nodelet (https://sketchfab.com/nodelet)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-toilet-b997255f4299486fa612c455bf3216d7
title: Low-poly toilet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Edges } from '@react-three/drei'

export default function Toilet(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/low-poly_toilet/scene.gltf')
    return (
        <group scale={[5, 5, 5]} ref={group} dispose={null}>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['toiled-material'].geometry}
                    material={nodes['toiled-material'].material}>
                    <Edges
                        color='rgb(200, 200, 200)'
                        threshold={30} />
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['toiled-material_1'].geometry}
                    material={nodes['toiled-material_1'].material}>
                    <Edges
                        color='rgb(200, 200, 200)'
                        threshold={30} />
                </mesh>
                <lineSegments geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['toiled-material_2'].geometry}
                    material={nodes['toiled-material_2'].material}>
                    <Edges
                        color='rgb(200, 200, 200)'
                        threshold={40} />
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('/low-poly_toilet/scene.gltf')