/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Starkster (https://sketchfab.com/parmaryash2599)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/colgate-toothpaste-tube-3a77c506eaea4e08a10f1d288d2ce45d
title: colgate toothpaste tube
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Toothpaste(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/colgate_toothpaste_tube/scene.gltf')
    return (
        <group scale={[0.002, 0.002, 0.002]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[0, 0, 0]} scale={[100, 58.81, 121.34]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_Material001_0.geometry}
                            material={materials['Material.001']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_Material004_0.geometry}
                            material={materials['Material.004']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_VEG_LOGO_0.geometry}
                            material={materials.VEG_LOGO}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_Material002_0.geometry}
                            material={materials['Material.002']}
                        />
                    </group>
                    <group position={[0, 0, -227.32]} rotation={[0, 0, 0]} scale={[40.41, 40.41, 40.41]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder001_Material003_0.geometry}
                            material={materials['Material.003']}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/colgate_toothpaste_tube/scene.gltf')