/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: IR4jeckkkkkk (https://sketchfab.com/IR4jeckkkkkk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/toothbrush1-a1b75957d10e4e79a3b18cdba0ecf038
title: Toothbrush.1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Toothbrush1(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/toothbrush.1/scene.gltf')
    return (
        <group scale={[0.01, 0.01, 0.01]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, -11.48, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial.geometry}
                            material={materials.material_1}
                        />
                    </group>
                    <group position={[-0.01, 65.04, 6.67]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_1.geometry}
                            material={materials.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/toothbrush.1/scene.gltf')