/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ஜCIHIRISஜ (https://sketchfab.com/crazy4creativity)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/brown-wicker-trash-bin-912cc19e1b20479ab14b37f95b97f715
title: Brown Wicker Trash Bin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Trashcan(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/brown_wicker_trash_bin/scene.gltf')
    return (
        <group scale={[0.15, 0.15, 0.15]} ref={group} dispose={null}>
            <group position={[-18.08, 11, 3.07]} rotation={[-0.11, 1.34, -3.04]} scale={[0.01, 0.01, 0.01]}>
                <group rotation={[-Math.PI, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Stereo_textured_mesh_Material0_0.geometry}
                        material={nodes.Stereo_textured_mesh_Material0_0.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Stereo_textured_mesh_Material0_0_1.geometry}
                        material={nodes.Stereo_textured_mesh_Material0_0_1.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Stereo_textured_mesh_Material0_0_2.geometry}
                        material={nodes.Stereo_textured_mesh_Material0_0_2.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Stereo_textured_mesh_Material0_0_3.geometry}
                        material={nodes.Stereo_textured_mesh_Material0_0_3.material}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Stereo_textured_mesh_Material0_0_4.geometry}
                        material={nodes.Stereo_textured_mesh_Material0_0_4.material}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/brown_wicker_trash_bin/scene.gltf')