/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: patrakeevasveta (https://sketchfab.com/patrakeevasveta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bath-with-sink-800d3c5569b94abfa2da7976504d589d
title: Bath with sink
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Edges } from '@react-three/drei'

export default function Tub(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/bath_with_sink/scene.gltf')
    return (
        <group scale={[4.5, 4, 4.5]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[-77.62, 10.27, 469.82]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 100, 100]}>
                        <group position={[0, 0.87, 0.71]} rotation={[0, 0, 0]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.sink_bath_0.geometry}
                                material={nodes.sink_bath_0.material}>
                                <Edges
                                    color='rgb(200, 200, 200)'
                                    threshold={25} />
                            </mesh>
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.bath_bath_0.geometry}
                            material={nodes.bath_bath_0.material}>
                            <Edges
                                color='rgb(200, 200, 200)'
                                threshold={25} />
                        </mesh>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/bath_with_sink/scene.gltf')