/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Whystler (https://sketchfab.com/Whystler)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/venus-poster-37b43d63676047e08416a0b4942219df
title: Venus Poster
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function VenusPoster(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/venus_poster/scene.gltf')
    return (
        <group scale={[0.035, 0.035, 0.035]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.material_frame}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.material_matting}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={materials.material_poster}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/venus_poster/scene.gltf')