/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nommoc (https://sketchfab.com/kikumi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/washing-machine-d279bf50fc3f41119d67d6f622555f3e
title: Washing Machine
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function WashingMachine(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/washing_machine-2/scene.gltf')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[2.5, 2.5, 2.5]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-0.01, 1.11, -0.29]}>
                        <group position={[0, 0, 0.22]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_16.geometry}
                                material={nodes.Object_16.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_17.geometry}
                                material={nodes.Object_17.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_18.geometry}
                                material={nodes.Object_18.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_19.geometry}
                                material={nodes.Object_19.material}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_14.geometry}
                            material={nodes.Object_14.material}
                        />
                    </group>
                    <group position={[-0.47, 1.11, 0.52]}>
                        <group position={[0.45, 0, 0.02]}>
                            <group position={[0, -0.03, 0.12]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_32.geometry}
                                    material={nodes.Object_32.material}
                                />
                            </group>
                            <group
                                position={[0, 0, 0.12]}
                                rotation={[Math.PI / 2, 0, 0]}
                                scale={[0.03, 0.03, 0.03]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_34.geometry}
                                    material={nodes.Object_34.material}
                                />
                            </group>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_29.geometry}
                                material={materials.glass}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_30.geometry}
                                material={materials['glass.001']}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_26.geometry}
                            material={nodes.Object_26.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_27.geometry}
                            material={nodes.Object_27.material}
                        />
                    </group>
                    <group position={[-0.35, 1.76, 0.2]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_38.geometry}
                            material={nodes.Object_38.material}
                        />
                    </group>
                    <group position={[0.64, 1.01, -0.03]} rotation={[0, 0, -0.04]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={nodes.Object_4.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5.geometry}
                            material={materials.plastic02}
                        />
                    </group>
                    <group position={[0.63, 1.29, -0.02]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_7.geometry}
                            material={nodes.Object_7.material}
                        />
                    </group>
                    <group position={[-0.01, 0.91, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={nodes.Object_9.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_10.geometry}
                            material={nodes.Object_10.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={nodes.Object_12.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_11.geometry}
                            material={nodes.Object_11.material}
                        />
                    </group>
                    <group position={[-0.01, 1.11, 0.51]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_21.geometry}
                            material={nodes.Object_21.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_22.geometry}
                            material={nodes.Object_22.material}
                        />
                    </group>
                    <group position={[0.41, 0.06, 0.36]} scale={[0.04, 0.04, 0.04]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_24.geometry}
                            material={nodes.Object_24.material}
                        />
                    </group>
                    <group position={[-0.01, 1.11, 0.51]} scale={[0.81, 0.81, 0.81]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_36.geometry}
                            material={materials['silver.001']}
                        />
                    </group>
                    <group position={[-0.01, 1.11, 0.52]} scale={[0.81, 0.81, 0.81]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_40.geometry}
                            material={nodes.Object_40.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/washing_machine-2/scene.gltf')
