/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Martin Ibbett (https://sketchfab.com/unyxium)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/wood-tray-857eb67de4114e899789eb17de16711a
title: Wood Tray
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WoodTray(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/wood_tray/scene.gltf')
    return (
        <group scale={[4, 4, 4]} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.bake_to}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/wood_tray/scene.gltf')